[CLIENT_SETUP]
client_ip = 127.0.0.1
path_to_buildfolder = ./
client_file = client_osx
# files in 'data_folder' used for GET | SET | DELETE
data_folder = data
client_count = 20
running_peer_list = running_peers.csv.txt
messaged_pool = messaged_peers.csv.txt
swap_folder = program_swap

