[LOGGER_SETUP]
logger_dir = 'log'

[PEER_SETUP]
script_path = 'EMPTY'
path_to_buildfolder = cmake-build-debug
peer_file = peer
running_peer_list = running_peers.csv.txt
swap_folder = program_swap

peer_count = 20
ip = 127.0.0.1

startport = 4100
endport = 5000

### First peer is always initialised with id=0
id_start = 1
id_end = 65000

### random_ids = 2 | linspaced-ids = 1 | linear-ids = 0
id_setting = 2

### random_dst peer = 1 | anchestor peer = 0
dst_peer = 0

### linear_ports = 0 | linear-spaced-ports = 1 | random ports = 2
port_range = 2
